server:
  port: 0
spring:
  application:
    name: product-service
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

# /actuator/refresh 요청을 통한 프로파일 불러오기 활성화
management:
  endpoints:
    web:
      exposure:
        include: refresh
  # zipkin 을 위한 옵션 추가
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0


message: "default message"